apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    service: backend-feed
